version: '3'

services:
  web:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin